-- Posts table — the agent writes drafts here, clients review in the iOS app

CREATE TABLE IF NOT EXISTS posts (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  client_id         UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  title             TEXT NOT NULL,
  slug              TEXT NOT NULL,
  meta_title        TEXT NOT NULL,
  meta_description  TEXT NOT NULL,
  target_keyword    TEXT NOT NULL,
  content           TEXT NOT NULL,
  excerpt           TEXT NOT NULL,
  status            TEXT NOT NULL DEFAULT 'generating'
                    CHECK (status IN ('generating', 'pending_review', 'approved', 'published', 'rejected')),
  rejection_note    TEXT,
  created_at        TIMESTAMPTZ DEFAULT now(),
  published_at      TIMESTAMPTZ
);

-- Index for the iOS app's primary query: "show me my pending posts"
CREATE INDEX idx_posts_client_status ON posts(client_id, status);

-- Index for deduplication: agent checks existing titles before generating
CREATE INDEX idx_posts_client_title ON posts(client_id, title);

-- Slug uniqueness per client
CREATE UNIQUE INDEX idx_posts_client_slug ON posts(client_id, slug);

-- RLS
ALTER TABLE posts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can read own posts"
  ON posts FOR SELECT
  USING (auth.uid() = client_id);

CREATE POLICY "Users can update own posts"
  ON posts FOR UPDATE
  USING (auth.uid() = client_id)
  WITH CHECK (auth.uid() = client_id);

CREATE POLICY "Service role full access"
  ON posts FOR ALL
  USING (auth.role() = 'service_role');

COMMENT ON TABLE posts IS 'Blog posts generated by the AI agent — reviewed by clients in the iOS app';
